name: b2
on: 
  push:
    paths:
      - '**/b2/*'
  pull_request:
    paths:
      - '**/b2/*'

jobs:
  b2-test: 
    name: Greeting # ジョブ名
    runs-on: ubuntu-latest # ジョブが実行される仮想環境
    steps:
      - run: |
          echo "b2"