name: bill
on: 
  push:
    paths:
      - '**/bill/*'
  pull_request:
    paths:
      - '**/bill/*'

jobs:
  bill-test: 
    name: Greeting # ジョブ名
    runs-on: ubuntu-latest # ジョブが実行される仮想環境
    steps:
      - run: |
          echo "bill"